# Configure Netlify to serve particular headers for certain routes
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
      Referrer-Policy = "origin-when-cross-origin"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type = "nosniff"
      # Multi-key header rules are expressed with multi-line strings.
      Content-Security-Policy = '''
      default-src 'self' https://p.trellocdn.com;
      connect-src 'self' https://p.trellocdn.com https://glp2.csrsinc.com https://fwittrello.csrsinc.com;
      script-src 'self' https://p.trellocdn.com https://glp2.csrsinc.com https://fwittrello.csrsinc.com;
      style-src 'self' https://p.trellocdn.com https://glp2.csrsinc.com https://fwittrello.csrsinc.com;
      frame-ancestors https://trello.com;'''

  # enable CORS on one of our string files to enable testing
[[headers]]
  for = "/en.json"
    [headers.values]
      Access-Control-Allow-Origin = "*"